"""Remove payment foreign key constraints

Revision ID: a609893a00df
Revises: 8f02d9f6c53a
Create Date: 2024-12-14 13:28:51.300998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a609893a00df'
down_revision = '8f02d9f6c53a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_from_account_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_to_account_fkey', 'payments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('payments_to_account_fkey', 'payments', 'internal_organization_bank_accounts', ['to_account'], ['uuid'])
    op.create_foreign_key('payments_from_account_fkey', 'payments', 'external_organization_bank_accounts', ['from_account'], ['uuid'])
    # ### end Alembic commands ###
